# config/routes.yaml

# home path
home:
    path: /
    controller: app\Controller\TrickController::index

# trick path
trick_show:
    path: /view/{titre}
    controller: App\Controller\TrickController::show

trick_showUser:
    path: /show/{titre}
    controller: App\Controller\TrickController::showUser

trick_showUserUpdate:
    path: /update/{titre}
    controller: App\Controller\TrickController::update

trick_showUserDelete:
    path: /delete/{titre}
    controller: App\Controller\TrickController::delete

# user path
user_update:
    path: /account/{username}/modify
    controller: App\Controller\UserController::update

user_delete:
    path: /account/{username}/unsubscribe
    controller: App\Controller\UserController::delete

# coment path

comment_create:
    path: /show/{titre}/post
    controller: App\Controller\CommentController::create